### ISSUE TITLE
Typo in IP address quoted in Step 5

### ISSUE THREAD

**Issue by CollinsSing** [freshworkstudio/node-tasmota-installer#1]
Noted a typo in Step 5 which should be 10.10.7.1 instead of 10.7.7.1. 
Anyway, your script is handy and helpful for me to flash 3 x SONOFF Basic R3 yesterday.

**Comment by gdespirito** [comment]
Thanks! Did it work for you?

**Comment by gdespirito** [comment]
Btw, i fixed it.

**Comment by CollinsSing** [comment]
> Thanks! Did it work for you?

Yes.  Your script works 100% and thanks for sharing.
